server:
  port: 8080
  context-path: /vegetables
name: zpp
age: 25
content: "name:${name},age:${age}"
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/vegetables?characterEncoding=utf8&useSSL=false
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

    thymeleaf:
       cache: false
       prefix: /templates/
       suffix: .html
